# Generated by Django 4.0.6 on 2022-08-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='id_dt',
            field=models.DateTimeField(),
        ),
    ]
