# Generated by Django 4.0.6 on 2022-08-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rapp', '0007_phones_call_duration_category_alter_phones_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='call_duration_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='id_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='oiv_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='snils',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='theme_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phones',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
